apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "shopping-cart-analytics"
spec:
  host: "shopping-cart-analytics"
  subsets:
  - name: v1
    labels:
      version: v1